plugins {
    id 'dev.architectury.loom'
    id 'architectury-plugin'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    // splitEnvironmentSourceSets()
}

configurations {
    common
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    modApi("com.terraformersmc:modmenu:17.0.0-beta.1")
    modApi("me.shedaniel.cloth:cloth-config-fabric:21.11.153") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    include project(":common")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": rootProject.minecraft_version,
                "loader_version": rootProject.loader_version
    }
}
tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
