@echo off
echo Killing all Java processes...
taskkill /F /IM java.exe 2>nul
echo Waiting a moment...
timeout /t 2 /nobreak >nul
echo Clearing stale Loom cache...
rmdir /S /Q "%USERPROFILE%\.gradle\caches\fabric-loom\1.21.11" 2>nul
echo Running build...
call gradlew.bat :common:compileJava
