plugins {
    id 'maven-publish'
}

subprojects {
    apply plugin: 'maven-publish'
    apply plugin: 'java'

    version = rootProject.mod_version
    group = rootProject.maven_group

    base {
        archivesName = rootProject.archives_base_name
    }

    repositories {
        // Loom automatically adds Minecraft and Fabric repos.
        // Only add repos for other mod dependencies here.
        maven { url "https://maven.terraformersmc.com/releases/" }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://libraries.minecraft.net/" }
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 21
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}
