org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.2.10-hotspot
org.gradle.configuration-cache=false

# Minecraft Version
minecraft_version=26.3
# Architectury Loom Version
loom_version=1.17-SNAPSHOT
# Fabric Loader Version
loader_version=0.19.5

# Mod Information
mod_version=2.3.0
maven_group=com.example
archives_base_name=soundvisualizer

# Dependencies
fabric_api_version=0.161.0+26.3
architectury_api_version=22.0.3
neoforge_version=26.3.0.31-beta
cloth_config_version=26.3.159
modmenu_version=21.0.0
mod_id=soundvisualizer
