org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.2.10-hotspot
org.gradle.configuration-cache=false

# Minecraft Version
minecraft_version=26.1.2
# Architectury Loom Version
loom_version=1.14-SNAPSHOT
# Fabric Loader Version
loader_version=0.19.3

# Mod Information
mod_version=2.1.0-beta.1
maven_group=com.example
archives_base_name=soundvisualizer

# Dependencies
fabric_api_version=0.153.0+26.1.2
architectury_api_version=20.0.7
neoforge_version=26.1.2.76
cloth_config_version=26.1.154
modmenu_version=18.0.0-beta.1
mod_id=soundvisualizer
