license="MIT"

[[mods]]
modId="soundvisualizer"
version="${version}"
displayName="Sound Visualizer"
description="HUD indicators for sound directions."
authors="G10W5"

[[mixins]]
config="soundvisualizer.mixins.json"

[[dependencies.soundvisualizer]]
    modId="minecraft"
    type="required"
    versionRange="[26.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soundvisualizer]]
    modId="architectury"
    type="required"
    versionRange="[20.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soundvisualizer]]
    modId="cloth_config"
    type="required"
    versionRange="[26.1.0,)"
    ordering="NONE"
    side="BOTH"
